Repository nextcloud/nextcloud-vue-dashboard, pull requests merged in 2020-09, with the labels that each got.

#40 Don't show user status if an overlay icon is set
  src/DashboardWidgetItem.vue
Labels: 3. to review, enhancement

#41 Empty content and half empty content
  src/DashboardWidget.vue
  src/DashboardWidgetItem.vue
Labels: 3. to review, enhancement

#42 Split DashboardWidgetItem 'item' prop
  src/DashboardWidget.vue
  src/DashboardWidgetItem.vue
Labels: 3. to review, enhancement

#44 v1.0.0
  package-lock.json
  package.json
Labels: 4. to release

#51 Make sure empty content message is rendered as simple text
  src/DashboardWidget.vue
Labels: 3. to review
